### ISSUE TITLE
Compilation error: cmd: unknown variable '$(PATH_OVERRIDE_SOONG)'

### ISSUE THREAD

**Issue by ghost** [CherishOS/android_manifest#15]
I try to compilate cherish os tiramisu, and have this error:

CHERISH_VERSION=
PLATFORM_VERSION=13
TARGET_PRODUCT=aosp_x86_64
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_GCC_VERSION=4.9
TARGET_ARCH=x86_64
TARGET_ARCH_VARIANT=x86_64
TARGET_CPU_VARIANT=
TARGET_2ND_ARCH=x86
TARGET_2ND_ARCH_VARIANT=x86_64
TARGET_2ND_CPU_VARIANT=
BUILD_ID=TP1A.220905.004
OUT_DIR=/home/oppro/cherrishos/out
PRODUCT_SOONG_NAMESPACES=device/generic/goldfish device/generic/goldfish-opengl hardware/google/camera hardware/google/camera/devices/EmulatedCamera

[100% 398/398] analyzing Android.bp files and generating ninja file at /home/oppro/cherrishos/out/soong/build.ninja
FAILED: /home/oppro/cherrishos/out/soong/build.ninja
cd "$(dirname "/home/oppro/cherrishos/out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "/home/oppro/cherrishos/out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "/home/oppro/cherrishos/out/soong"     --out 
"/home/oppro/cherrishos/out"     -o /home/oppro/cherrishos/out/soong/build.ninja --globListDir build --globFile /home/oppro/cherrishos/out/soong/globs-build.ninja -t -l /home/oppro/cherrishos/out/.module_paths/Android.bp.list --available_env /home/oppro/cherrishos/out/soong
/soong.environment.available --used_env /home/oppro/cherrishos/out/soong/soong.environment.used.build Android.bp
error: vendor/cherish/build/soong/Android.bp:24:8: module "generated_kernel_includes": cmd: unknown variable '$(PATH_OVERRIDE_SOONG)'
22:13:57 soong bootstrap failed with: exit status 1

#### failed to build some targets (01:00 (mm:ss)) ####

Please help.

**Comment by VTVishwanath** [comment]
How did you fix this issue? @ghost
