### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by kavencat** [CherishOS/android_manifest#27]
FAILED: //device/xiaomi/wayne/gps/utils:libgps.utils clang++ loc_log.cpp
Outputs: out/soong/.intermediates/device/xiaomi/wayne/gps/utils/libgps.utils/android_vendor.35_arm64_armv8-a_shared_cfi/e560d7b19ebf7276b3e850d3d346dec8/obj/device/xiaomi/wayne/gps/utils/loc_log.o
Error: exited with code: 1
Command: PWD=/proc/self/cwd /usr/bin/ccache prebuilts/clang/host/linux-x86/clang-r498229b/bin/clang++ -c -D__ANDROID_VNDK__ -D__ANDROID_VENDOR__ -D__ANDROID_VENDOR_API__=34  -Werror=implicit-function-declaration -O2 -Wall -Wextra -Winit-self -Wpointer-arith -Wunguarded-availability -Werror=date-time -Werror=int-conversion -Werror=pragma-pack -Werror=pragma-pack-suspicious-include -Werror=sizeof-array-div -Werror=string-plus-int -Werror=unreachable-code-loop-increment -Wno-error=deprecated-declarations -Wno-c99-designator -Wno-gnu-folding-constant -Wno-inconsistent-missing-override -Wno-error=reorder-init-list -Wno-reorder-init-list -Wno-sign-compare -Wno-unused -DANDROID -DNDEBUG -UDEBUG -D__compiler_offsetof=__builtin_offsetof -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -faddrsig -fdebug-default-version=5 -fcolor-diagnostics -ffp-contract=off -fno-exceptions -fno-strict-aliasing -fmessage-length=0 -gsimple-template-names -gz=zstd -no-canonical-prefixes -fdebug-prefix-map=/proc/self/cwd= -ftrivial-auto-var-init=zero -Wno-unused-command-line-argument -g -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=format-security -nostdlibinc -fdebug-info-for-profiling -march=armv8-a  -target aarch64-linux-android35 -DANDROID_STRICT -fPIC -Wimplicit-fallthrough -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-gnu-include-next -fvisibility-inlines-hidden  -Idevice/xiaomi/wayne/gps/utils -Isystem/core/libutils/include -Isystem/libbase/include -Iexternal/fmtlib/include -Isystem/core/libcutils/include_outside_system -Isystem/logging/liblog/include_vndk -Isystem/core/libprocessgroup/include -Isystem/core/libsystem/include -Idevice/xiaomi/wayne/gps/pla/android -Idevice/xiaomi/wayne/gps/location -Iexternal/libcxxabi/include -Isystem/core/libutils/binder/include -Isystem/core/libcutils/include -Iexternal/libcxx/include -isystem out/soong/.intermediates/bionic/libc/libc/android_vendor.35_arm64_armv8-a_shared/gen/include -isystem bionic/libc/kernel/uapi/asm-arm64 -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -fno-short-enums -D_ANDROID_ -Werror -Wno-error=unused-parameter -Wno-error=macro-redefined -Wno-error=reorder -Wno-error=missing-braces -Wno-error=self-assign -Wno-error=enum-conversion -Wno-error=logical-op-parentheses -Wno-error=null-arithmetic -Wno-error=null-conversion -Wno-error=parentheses-equality -Wno-error=undefined-bool-conversion -Wno-error=tautological-compare -Wno-error=switch -Wno-error=date-time -flto -fsanitize-cfi-cross-dso -fsanitize-ignorelist=external/compiler-rt/lib/cfi/cfi_blocklist.txt -fvisibility=default -fsanitize=bounds,null,unreachable,integer,cfi -fsanitize-trap=all -fsanitize-minimal-runtime -fno-sanitize-trap=integer,undefined -fno-sanitize-recover=integer,undefined -fno-sanitize=implicit-integer-sign-change -fno-sanitize=unsigned-shift-base -std=gnu++20 -fno-rtti  -Werror=bool-operation -Werror=format-insufficient-args -Werror=implicit-int-float-conversion -Werror=int-in-bool-context -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=xor-used-as-pow -Wno-void-pointer-to-enum-cast -Wno-void-pointer-to-int-cast -Wno-pointer-to-int-cast -Werror=fortify-source -Werror=address-of-temporary -Werror=null-dereference -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-implicit-int-float-conversion -Wno-tautological-overlap-compare -Wno-deprecated-copy -Wno-range-loop-construct -Wno-zero-as-null-pointer-constant -Wno-deprecated-anon-enum-enum-conversion -Wno-pessimizing-move -Wno-non-c-typedef-for-linkage -Wno-align-mismatch -Wno-error=unused-but-set-variable -Wno-error=unused-but-set-parameter -Wno-error=deprecated-builtins -Wno-error=deprecated -Wno-error=single-bit-bitfield-constant-conversion -Wno-error=enum-constexpr-conversion  -MD -MF out/soong/.intermediates/device/xiaomi/wayne/gps/utils/libgps.utils/android_vendor.35_arm64_armv8-a_shared_cfi/e560d7b19ebf7276b3e850d3d346dec8/obj/device/xiaomi/wayne/gps/utils/loc_log.o.d -o out/soong/.intermediates/device/xiaomi/wayne/gps/utils/libgps.utils/android_vendor.35_arm64_armv8-a_shared_cfi/e560d7b19ebf7276b3e850d3d346dec8/obj/device/xiaomi/wayne/gps/utils/loc_log.o device/xiaomi/wayne/gps/utils/loc_log.cpp
Output:
In file included from device/xiaomi/wayne/gps/utils/loc_log.cpp:36:
In file included from device/xiaomi/wayne/gps/utils/log_util.h:34:
[1mdevice/xiaomi/wayne/gps/pla/android/loc_pla.h:43:10: [0m[0;1;31mfatal error: [0m[1m'cutils/threads.h' file not found[0m
#include <cutils/threads.h>
[0;1;32m         ^~~~~~~~~~~~~~~~~~
[0m1 error generated.

FAILED: //device/xiaomi/wayne/gps/utils:libgps.utils clang++ loc_cfg.cpp
Outputs: out/soong/.intermediates/device/xiaomi/wayne/gps/utils/libgps.utils/android_vendor.35_arm64_armv8-a_shared_cfi/e560d7b19ebf7276b3e850d3d346dec8/obj/device/xiaomi/wayne/gps/utils/loc_cfg.o
Error: exited with code: 1
Command: PWD=/proc/self/cwd /usr/bin/ccache prebuilts/clang/host/linux-x86/clang-r498229b/bin/clang++ -c -D__ANDROID_VNDK__ -D__ANDROID_VENDOR__ -D__ANDROID_VENDOR_API__=34  -Werror=implicit-function-declaration -O2 -Wall -Wextra -Winit-self -Wpointer-arith -Wunguarded-availability -Werror=date-time -Werror=int-conversion -Werror=pragma-pack -Werror=pragma-pack-suspicious-include -Werror=sizeof-array-div -Werror=string-plus-int -Werror=unreachable-code-loop-increment -Wno-error=deprecated-declarations -Wno-c99-designator -Wno-gnu-folding-constant -Wno-inconsistent-missing-override -Wno-error=reorder-init-list -Wno-reorder-init-list -Wno-sign-compare -Wno-unused -DANDROID -DNDEBUG -UDEBUG -D__compiler_offsetof=__builtin_offsetof -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -faddrsig -fdebug-default-version=5 -fcolor-diagnostics -ffp-contract=off -fno-exceptions -fno-strict-aliasing -fmessage-length=0 -gsimple-template-names -gz=zstd -no-canonical-prefixes -fdebug-prefix-map=/proc/self/cwd= -ftrivial-auto-var-init=zero -Wno-unused-command-line-argument -g -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=format-security -nostdlibinc -fdebug-info-for-profiling -march=armv8-a  -target aarch64-linux-android35 -DANDROID_STRICT -fPIC -Wimplicit-fallthrough -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-gnu-include-next -fvisibility-inlines-hidden  -Idevice/xiaomi/wayne/gps/utils -Isystem/core/libutils/include -Isystem/libbase/include -Iexternal/fmtlib/include -Isystem/core/libcutils/include_outside_system -Isystem/logging/liblog/include_vndk -Isystem/core/libprocessgroup/include -Isystem/core/libsystem/include -Idevice/xiaomi/wayne/gps/pla/android -Idevice/xiaomi/wayne/gps/location -Iexternal/libcxxabi/include -Isystem/core/libutils/binder/include -Isystem/core/libcutils/include -Iexternal/libcxx/include -isystem out/soong/.intermediates/bionic/libc/libc/android_vendor.35_arm64_armv8-a_shared/gen/include -isystem bionic/libc/kernel/uapi/asm-arm64 -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -fno-short-enums -D_ANDROID_ -Werror -Wno-error=unused-parameter -Wno-error=macro-redefined -Wno-error=reorder -Wno-error=missing-braces -Wno-error=self-assign -Wno-error=enum-conversion -Wno-error=logical-op-parentheses -Wno-error=null-arithmetic -Wno-error=null-conversion -Wno-error=parentheses-equality -Wno-error=undefined-bool-conversion -Wno-error=tautological-compare -Wno-error=switch -Wno-error=date-time -flto -fsanitize-cfi-cross-dso -fsanitize-ignorelist=external/compiler-rt/lib/cfi/cfi_blocklist.txt -fvisibility=default -fsanitize=bounds,null,unreachable,integer,cfi -fsanitize-trap=all -fsanitize-minimal-runtime -fno-sanitize-trap=integer,undefined -fno-sanitize-recover=integer,undefined -fno-sanitize=implicit-integer-sign-change -fno-sanitize=unsigned-shift-base -std=gnu++20 -fno-rtti  -Werror=bool-operation -Werror=format-insufficient-args -Werror=implicit-int-float-conversion -Werror=int-in-bool-context -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=xor-used-as-pow -Wno-void-pointer-to-enum-cast -Wno-void-pointer-to-int-cast -Wno-pointer-to-int-cast -Werror=fortify-source -Werror=address-of-temporary -Werror=null-dereference -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-implicit-int-float-conversion -Wno-tautological-overlap-compare -Wno-deprecated-copy -Wno-range-loop-construct -Wno-zero-as-null-pointer-constant -Wno-deprecated-anon-enum-enum-conversion -Wno-pessimizing-move -Wno-non-c-typedef-for-linkage -Wno-align-mismatch -Wno-error=unused-but-set-variable -Wno-error=unused-but-set-parameter -Wno-error=deprecated-builtins -Wno-error=deprecated -Wno-error=single-bit-bitfield-constant-conversion -Wno-error=enum-constexpr-conversion  -MD -MF out/soong/.intermediates/device/xiaomi/wayne/gps/utils/libgps.utils/android_vendor.35_arm64_armv8-a_shared_cfi/e560d7b19ebf7276b3e850d3d346dec8/obj/device/xiaomi/wayne/gps/utils/loc_cfg.o.d -o out/soong/.intermediates/device/xiaomi/wayne/gps/utils/libgps.utils/android_vendor.35_arm64_armv8-a_shared_cfi/e560d7b19ebf7276b3e850d3d346dec8/obj/device/xiaomi/wayne/gps/utils/loc_cfg.o device/xiaomi/wayne/gps/utils/loc_cfg.cpp
Output:
In file included from device/xiaomi/wayne/gps/utils/loc_cfg.cpp:43:
[1mdevice/xiaomi/wayne/gps/pla/android/loc_pla.h:43:10: [0m[0;1;31mfatal error: [0m[1m'cutils/threads.h' file not found[0m
#include <cutils/threads.h>
[0;1;32m         ^~~~~~~~~~~~~~~~~~
[0m1 error generated.

FAILED: //device/xiaomi/wayne/doze:XiaomiDoze javac [common]
Outputs: out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/XiaomiDoze.jar out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/anno.srcjar
Error: exited with code: 1
Command: rm -rf "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/classes" "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/anno" "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/anno.srcjar.tmp" "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/srcjars" "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/XiaomiDoze.jar.tmp" && mkdir -p "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/classes" "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/anno" "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/srcjars" && out/host/linux-x86/bin/zipsync -d out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/srcjars -l out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/srcjars/list -f "*.java" out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/gen/android/R.srcjar && (if [ -s out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/srcjars/list ] || [ -s out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/XiaomiDoze.jar.rsp ] ; then out/host/linux-x86/bin/soong_javac_wrapper prebuilts/jdk/jdk17/linux-x86/bin/javac -J-Xmx4096M -J-XX:OnError="cat hs_err_pid%p.log" -J-XX:CICompilerCount=6 -J-XX:+UseDynamicNumberOfGCThreads -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath "" -g -XDskipDuplicateBridges=true -XDstringConcat=inline  -proc:none -g:source,lines -Xlint:-dep-ann --system=out/soong/.intermediates/build/soong/java/core-libraries/stable-core-platform-api-stubs-system-modules/android_common/system -classpath out/soong/.intermediates/frameworks/base/ext/android_common/turbine-combined/ext.jar:out/soong/.intermediates/frameworks/base/framework/android_common/turbine-combined/framework.jar:out/soong/.intermediates/packages/resources/devicesettings/org.lineageos.settings.resources/android_common/turbine-combined/org.lineageos.settings.resources.jar -source 17 -target 17 -d out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/classes -s out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/anno @out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/XiaomiDoze.jar.rsp @out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/srcjars/list ; fi ) && out/host/linux-x86/bin/soong_zip -jar -o out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/anno.srcjar.tmp -C out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/anno -D out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/anno && out/host/linux-x86/bin/soong_zip -jar -o out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/XiaomiDoze.jar.tmp -C out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/classes -D out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/classes && if ! cmp -s "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/XiaomiDoze.jar.tmp" "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/XiaomiDoze.jar"; then mv "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/XiaomiDoze.jar.tmp" "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/XiaomiDoze.jar"; fi && if ! cmp -s "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/anno.srcjar.tmp" "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/anno.srcjar"; then mv "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/anno.srcjar.tmp" "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/anno.srcjar"; fi && rm -rf "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/srcjars" "out/soong/.intermediates/device/xiaomi/wayne/doze/XiaomiDoze/android_common/782bb8d1c3056f27f73d5d6bc57b878a/javac/classes"
Output:
[1mdevice/xiaomi/wayne/doze/src/org/lineageos/settings/doze/DozeSettingsActivity.java:23: [31m错误:[0m[1m 找不到符号[0m
import com.android.settingslib.widget.R;
[1m                                     [32m^[0m[1m[0m
  符号:   类 R
  位置: 程序包 com.android.settingslib.widget
[1mdevice/xiaomi/wayne/doze/src/org/lineageos/settings/doze/DozeSettingsFragment.java:37: [31m错误:[0m[1m 找不到符号[0m
import com.android.settingslib.widget.OnMainSwitchChangeListener;
[1m                                     [32m^[0m[1m[0m
  符号:   类 OnMainSwitchChangeListener
  位置: 程序包 com.android.settingslib.widget
[1mdevice/xiaomi/wayne/doze/src/org/lineageos/settings/doze/DozeSettingsFragment.java:40: [31m错误:[0m[1m 找不到符号[0m
        implements OnMainSwitchChangeListener, OnPreferenceChangeListener {
[1m                   [32m^[0m[1m[0m
  符号: 类 OnMainSwitchChangeListener
[1mdevice/xiaomi/wayne/doze/src/org/lineageos/settings/doze/DozeSettingsFragment.java:64: [31m错误:[0m[1m 不兼容的类型: DozeSettingsFragment无法转换为OnCheckedChangeListener[0m
        mSwitchBar.addOnSwitchChangeListener(this);
[1m                                             [32m^[0m[1m[0m
[1mdevice/xiaomi/wayne/doze/src/org/lineageos/settings/doze/DozeSettingsFragment.java:98: [31m错误:[0m[1m 方法不会覆盖或实现超类型的方法[0m
    @Override
[1m    [32m^[0m[1m[0m
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些消息已经过简化; 请使用 -Xdiags:verbose 重新编译以获得完整输出
5 个错误

**Comment by NextWork123** [comment]
hello, for fix that issue you can go on the `device/xiaomi/wayne/gps/pla/android/loc_pla.h` and remove that `#include <cutils/threads.h>`

Best Regards,
NextWorks
