### ISSUE TITLE
isn't fetching.

### ISSUE THREAD

**Issue by NextWork123** [CherishOS/android_manifest#28]
Hello, i tried to repo syncing but isn't fetching the framework/base and some other repos of aosp how can i fix?

```
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 7527 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
error: Cannot fetch android_frameworks_base 
```

**Comment by psavarmattas** [comment]
That's an internet error. Just resync

**Comment by NextWork123** [comment]
> resync

tried with my isp and with another isp of my friend we have same issue. I have iliad and one my friend have wind i use too cloudflare warp and other vpns but the issue is there anyway

**Comment by psavarmattas** [comment]
I had this same issue and the best way was to resync or nuke the whole source and fresh sync. Nothing else you see online would hel I tried everything.

**Comment by NextWork123** [comment]
> I had this same issue and the best way was to resync or nuke the whole source and fresh sync. Nothing else you see online would hel I tried everything.

it can be because i use wsl? i think isn't that the issue no?

**Comment by psavarmattas** [comment]
I don't think wsl is the culprit here as in my native fedora machine also this issue comes up sometimes

**Comment by NextWork123** [comment]
> I don't think wsl is the culprit here as in my native fedora machine also this issue comes up sometimes

now i'm trying to repo sync -j1 to see if i have some issue with doing parallel things and i nuked aswell the source so i do fresh sync

**Comment by psavarmattas** [comment]
Try -j4

**Comment by NextWork123** [comment]
> Try -j4

i already started with j1 i leave that if it fails again i gonna try with -j4

**Comment by NextWork123** [comment]
I repo synced with -j1 and is all fine thanks again for the support @psavarmattas
