### ISSUE TITLE
FAILED: Target vendor fs image: out/target/product/wayne/vendor.img

### ISSUE THREAD

**Issue by kavencat** [CherishOS/android_manifest#30]
FAILED: Target vendor fs image: out/target/product/wayne/vendor.img
Outputs: out/target/product/wayne/vendor.img
Error: exited with code: 1
Command: /bin/bash -c "(mkdir -p out/target/product/wayne/vendor ) && (mkdir -p out/target/product/wayne/obj/PACKAGING/vendor_intermediates && rm -rf out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"vendor_fs_type=erofs\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"vendor_disable_sparse=true\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"vendor_selinux_fc=out/target/product/wayne/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"building_vendor_image=true\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"ext_mkuserimg=mkuserimg_mke2fs\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"fs_type=ext4\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"extfs_sparse_flag=-s\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"erofs_sparse_flag=-s\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"squashfs_sparse_flag=-s\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"f2fs_sparse_flag=-S\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"erofs_default_compressor=lz4\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"erofs_pcluster_size=262144\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"root_dir=out/target/product/wayne/root\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"use_dynamic_partition_size=true\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"skip_fsck=true\" >>  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (sort -o  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt  out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (PATH=out/host/linux-x86/bin/:system/extras/ext4_utils/:\$PATH out/host/linux-x86/bin/build_image --input-directory-filter-file out/target/product/wayne/obj/PACKAGING/vendor_intermediates/file_list.txt out/target/product/wayne/vendor out/target/product/wayne/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt out/target/product/wayne/vendor.img out/target/product/wayne/system ) && (true )"
Output:
rfs/msm/adsp/: not normalized

**Comment by Theimposter65** [comment]
how did you fix it?

**Comment by kavencat** [comment]
https://github.com/kavencat/android_device_xiaomi_wayne/commit/d9f55624d77555d10e05790c5afbb766bef251f4
